repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.19.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.1'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
#-   repo: https://github.com/tox-dev/pyproject-fmt
#    rev: 2.1.4
#    hooks:
#      - id: pyproject-fmt
#-   repo: https://github.com/abravalheri/validate-pyproject
#    rev: v0.18
#    hooks:
#      - id: validate-pyproject
